DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS colecao;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE colecao (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  autor_id INTEGER NOT NULL,
  criado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nome TEXT NOT NULL,
  tipo_objeto TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 1,
  descricao TEXT,
  FOREIGN KEY (autor_id) REFERENCES user (id)
);